// <auto-generated />
using System;
using AiImageTaskManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiImageTaskManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603092733_AddUsersAndJwtOwnership")]
    partial class AddUsersAndJwtOwnership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("AiImageTaskManager.Domain.Entities.ApiTestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ApiTestCases");
                });

            modelBuilder.Entity("AiImageTaskManager.Domain.Entities.ApiTestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualResponseBody")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActualStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiTestCaseId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApiTestCaseId");

                    b.ToTable("ApiTestRuns");
                });

            modelBuilder.Entity("AiImageTaskManager.Domain.Entities.GeneratedImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageGenerationTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImageGenerationTaskId");

                    b.ToTable("GeneratedImages");
                });

            modelBuilder.Entity("AiImageTaskManager.Domain.Entities.ImageGenerationTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CfgScale")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NegativePrompt")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Steps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ImageGenerationTasks");
                });

            modelBuilder.Entity("AiImageTaskManager.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AiImageTaskManager.Domain.Entities.ApiTestCase", b =>
                {
                    b.HasOne("AiImageTaskManager.Domain.Entities.User", "User")
                        .WithMany("ApiTestCases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiImageTaskManager.Domain.Entities.ApiTestRun", b =>
                {
                    b.HasOne("AiImageTaskManager.Domain.Entities.ApiTestCase", "ApiTestCase")
                        .WithMany("Runs")
                        .HasForeignKey("ApiTestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiTestCase");
                });

            modelBuilder.Entity("AiImageTaskManager.Domain.Entities.GeneratedImage", b =>
                {
                    b.HasOne("AiImageTaskManager.Domain.Entities.ImageGenerationTask", "ImageGenerationTask")
                        .WithMany("GeneratedImages")
                        .HasForeignKey("ImageGenerationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageGenerationTask");
                });

            modelBuilder.Entity("AiImageTaskManager.Domain.Entities.ImageGenerationTask", b =>
                {
                    b.HasOne("AiImageTaskManager.Domain.Entities.User", "User")
                        .WithMany("ImageGenerationTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiImageTaskManager.Domain.Entities.ApiTestCase", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("AiImageTaskManager.Domain.Entities.ImageGenerationTask", b =>
                {
                    b.Navigation("GeneratedImages");
                });

            modelBuilder.Entity("AiImageTaskManager.Domain.Entities.User", b =>
                {
                    b.Navigation("ApiTestCases");

                    b.Navigation("ImageGenerationTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
