@baseUrl=https://localhost:7074
@dockerBaseUrl=http://localhost:8080
@token=PASTE_LOCAL_TOKEN_HERE
@dockerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJkb2NrZXItdGVzdEBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJEb2NrZXIgVGVzdCBVc2VyIiwiZXhwIjoxNzgwNTA0MTEyLCJpc3MiOiJBaUltYWdlVGFza01hbmFnZXIiLCJhdWQiOiJBaUltYWdlVGFza01hbmFnZXJDbGllbnQifQ.MEnNCgLTw4e4BJ0SWSXLCV2Adu3-tGluYyeFHE0UkS0

### Local Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "P@ssw0rd123"
}

### Local Me
GET {{baseUrl}}/api/auth/me
Authorization: Bearer {{token}}

### Docker Register
POST {{dockerBaseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "docker-test@example.com",
  "displayName": "Docker Test User",
  "password": "P@ssw0rd123"
}

### Docker Login
POST {{dockerBaseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "docker-test@example.com",
  "password": "P@ssw0rd123"
}

### Docker Me
GET {{dockerBaseUrl}}/api/auth/me
Authorization: Bearer {{dockerToken}}

### Docker Create image task
POST {{dockerBaseUrl}}/api/image-tasks
Content-Type: application/json
Authorization: Bearer {{dockerToken}}

{
  "prompt": "a realistic train running on railway tracks",
  "negativePrompt": "blurry, low quality",
  "width": 512,
  "height": 512,
  "steps": 20,
  "cfgScale": 7,
  "seed": 12345
}

  ### Docker Get image tasks
GET {{dockerBaseUrl}}/api/image-tasks
Authorization: Bearer {{dockerToken}}